package com.ai.Email.Template.Generator.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;
import org.json.JSONObject;

import com.ai.Email.Template.Generator.client.GroqClient;
import com.ai.Email.Template.Generator.model.EmailRequest;

@RestController
@RequestMapping("/api/v1/email")
public class HelloController {

    @Autowired
    private GroqClient groqClient;

    @PostMapping("/generate")
    public String generateEmail(@RequestBody EmailRequest request) {

        // ✅ Strong prompt (STRICT JSON)
        String prompt = """
        You are a professional email generator.

        Return ONLY valid JSON.
        No markdown.
        No explanation.

        Format:
        {
          "subject": "...",
          "body": "...",
          "cta": "...",
          "tone": "professional"
        }

        User Input:
        """ + request.getPrompt();

        // ✅ Call Groq API
        String response = groqClient.callAI(prompt);

        // ✅ Clean unwanted formatting
        String content = response
                .replace("```json", "")
                .replace("```", "")
                .trim();

        // ✅ Parse JSON
        JSONObject json = new JSONObject(content);

        String subject = json.getString("subject");
        String body = json.getString("body");
        String cta = json.getString("cta");

        // ✅ Return Premium HTML
        return buildHtml(subject, body, cta);
    }

    // ✅ Clean HTML builder
    private String buildHtml(String subject, String body, String cta) {

        return """
        <!DOCTYPE html>
        <html>
        <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>

        <body style="margin:0;padding:0;background:#f4f6f8;font-family:Arial,sans-serif;">

            <table width="100%%" cellpadding="0" cellspacing="0">
                <tr>
                    <td align="center">

                        <table width="600" style="background:#ffffff;border-radius:10px;overflow:hidden">

                            <!-- HEADER -->
                            <tr>
                                <td style="
                                    background:linear-gradient(90deg,#667eea,#764ba2);
                                    padding:20px;
                                    color:#fff;
                                    text-align:center;
                                    font-size:22px;
                                    font-weight:bold;">
                                    %s
                                </td>
                            </tr>

                            <!-- BODY -->
                            <tr>
                                <td style="padding:30px;color:#333;font-size:16px;line-height:1.6;">
                                    %s
                                </td>
                            </tr>

                            <!-- CTA -->
                            <tr>
                                <td align="center" style="padding:20px;">
                                    <a href="#" style="
                                        background:#667eea;
                                        color:#fff;
                                        padding:12px 25px;
                                        text-decoration:none;
                                        border-radius:25px;
                                        font-weight:bold;">
                                        %s
                                    </a>
                                </td>
                            </tr>

                            <!-- FOOTER -->
                            <tr>
                                <td style="padding:15px;text-align:center;font-size:12px;color:#999;">
                                    Generated by AI Email Engine
                                </td>
                            </tr>

                        </table>

                    </td>
                </tr>
            </table>

        </body>
        </html>
        """.formatted(subject, body, cta);
    }
}